language: node_js
node_js:
  - 0.10

before_script:
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install -g grunt
  - bower install
  - grunt ngconstant:production
  - npm install -g codeclimate-test-reporter

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

addons:
  code_climate:
    repo_token: d9332d9216171bc23fd790cfe9b72748190bc7823758e20e201db9eaaa2e26af
